#!/usr/bin/env python3
# Python program to demonstrate 
# sys.argv 
import sys 

print("This is the name of the program:", sys.argv[0]) 

print("Argument List:", str(sys.argv)) 

for arg in sys.argv:
	if arg != '-b':
		sys.argv.remove(arg)
		sys.argv.insert(0, None)
if len(sys.argv) != 0:
	while sys.argv[sys.argv.count(None)-1] == None:
		sys.argv.pop(sys.argv.count(None)-1)
		if len(sys.argv) == 0:
			break	
	
print(sys.argv)